name: Build and Deploy Task App

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Add this to GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }} # Add this to GitHub Secrets

    # Build and Push Backend Docker Image
    - name: Build and Push Backend Image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/taskapp-backend:latest

    # Build and Push Frontend Docker Image
    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/taskapp-frontend:latest

    # Deploy Backend (example via SSH)
    - name: Deploy Backend via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/taskapp-backend:latest
          docker stop taskapp-backend || true
          docker rm taskapp-backend || true
          docker run -d --name taskapp-backend -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/taskapp-backend:latest

    # Deploy Frontend (example via SSH)
    - name: Deploy Frontend via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/taskapp-frontend:latest
          docker stop taskapp-frontend || true
          docker rm taskapp-frontend || true
          docker run -d --name taskapp-frontend -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/taskapp-frontend:latest
